version: '2'

services:
  inversion:
    image: inversion
    build: .
    container_name: inversion
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=inversion_db
      - DATABASE_USER=compose-postgres
      - DATABASE_PASSWORD=compose-postgres
    depends_on:
      - db
  db:
    restart: always
    image: 'postgres:13.1-alpine'
    container_name: inversion__db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inversion_db
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres